# Generated by Django 3.2.6 on 2021-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210810_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='type',
            field=models.ManyToManyField(to='services.Type'),
        ),
    ]
