# Generated by Django 3.2.6 on 2021-08-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_materials_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='services.type'),
            preserve_default=False,
        ),
    ]
