# Generated by Django 3.2.6 on 2021-08-11 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_materials_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_details',
            name='city',
        ),
        migrations.AddField(
            model_name='card_details',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.city'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='card_details',
            name='materials',
        ),
        migrations.AddField(
            model_name='card_details',
            name='materials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.materials'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='card_details',
            name='type',
        ),
        migrations.AddField(
            model_name='card_details',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.type'),
            preserve_default=False,
        ),
    ]
