# Generated by Django 3.2.6 on 2021-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210811_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='euros',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='golds',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='dollars',
            name='buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dollars',
            name='sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='euros',
            name='buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='euros',
            name='publish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='euros',
            name='sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golds',
            name='buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golds',
            name='publish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='golds',
            name='sell',
            field=models.IntegerField(default=0),
        ),
    ]
