# Generated by Django 3.2.6 on 2021-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20210811_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='img',
            field=models.ImageField(default=1234, upload_to='%Y/%M/%d'),
            preserve_default=False,
        ),
    ]
