# Generated by Django 3.2.6 on 2021-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_type_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='img',
            field=models.ImageField(blank=True, upload_to='%Y/%M/%d'),
        ),
    ]
