# Generated by Django 3.2.6 on 2021-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_type_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.ImageField(blank=True, upload_to='City/%Y/%M/%d'),
        ),
        migrations.AddField(
            model_name='materials',
            name='img',
            field=models.ImageField(blank=True, upload_to='Materials/%Y/%M/%d'),
        ),
        migrations.AlterField(
            model_name='type',
            name='img',
            field=models.ImageField(blank=True, upload_to='Type/%Y/%M/%d'),
        ),
    ]
