# Generated by Django 3.2.6 on 2021-08-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20210812_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_in_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.city')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.materials')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.type')),
            ],
        ),
    ]
