# Generated by Django 3.2.6 on 2021-08-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_show_in_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.city')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.dollars')),
            ],
        ),
    ]
