# Generated by Django 3.2.6 on 2021-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_golds_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='score_for_gold',
            field=models.IntegerField(default=21),
        ),
    ]
