# Generated by Django 3.2.6 on 2021-08-16 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0020_auto_20210814_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='informtions',
            field=models.TextField(default='|link id| |for dollars = 1 and set name (دولار)| |for Euros = 2 and set name (يورو)| |for golds = 3 and set name (ذهب)|  |for turkish = 4 and set name (ليرة تركية)|  |for saudi = 5 and set name (ريال سعودي)|'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='accounts/%Y/M%/%d', verbose_name='صورة ملف الشخصي')),
                ('city', models.CharField(blank=True, max_length=50)),
                ('is_actived', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='Confirm_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('is_finshed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.userprofile')),
            ],
        ),
    ]
