# Generated by Django 3.2.6 on 2021-08-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_account',
            name='key',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='accounts/profile_n.jpg', upload_to='accounts/%Y/%M/%d', verbose_name='صورة ملف الشخصي'),
        ),
    ]
