# Generated by Django 3.2.6 on 2021-08-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210821_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='accounts/user.png', upload_to='accounts/%Y/%M/%d', verbose_name='صورة ملف الشخصي'),
        ),
    ]
