# Generated by Django 3.2.6 on 2021-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='user.png', upload_to='accounts/%Y/%M/%d', verbose_name='صورة ملف الشخصي'),
        ),
    ]
